source "http://ruby.taobao.org"

gem "cuba"
gem "hiredis"
gem "ohm"
gem "slim"
gem "tilt", "1.3.3"
gem "rack", "1.4.1"

group :development, :test do
  gem "nokogiri", "1.5.5"
  gem "rack-test", "0.6.1"
  gem 'capybara'
  gem "ffaker"
  gem 'machinist', "~>1.0.6"
  gem "rspec", "2.10.0"
  gem "rspec-core", "2.10.1"
  gem "rspec-expectations", "2.10.0"
  gem "rspec-mocks", "2.10.1"
  gem "addressable", "2.2.8"
  gem "ffi", "1.0.11"
  gem "childprocess", "0.3.3"
  gem "multi_json", "1.3.6"
  gem "mime-types", "1.19"
  gem "shotgun"
end
