source "http://ruby.taobao.org"

gem "cuba"
gem "slim"
gem "tilt"
gem "ohm"
gem "hiredis"

group :development, :test do
  gem 'capybara'
  gem "ffaker"
  gem 'rspec'
  gem 'machinist', "~>1.0.6"
  gem 'unicorn'
  gem "shotgun"
end
