source "http://rubygems.org"
gem "sinatra"
gem "sequel"
gem "amalgalite"
gem "haml"

group :development, :test do
  gem 'rspec'
  gem 'steak'
  gem 'capybara'
  gem "faker"
  gem 'spawn'
  gem 'spork', '~> 0.9.0.rc'
end
