source "http://rubygems.org"
gem "sinatra", "~> 1.2.0"
gem "sequel"
gem "slim", '~> 1.0'
gem "pg"
gem "forme"

group :development, :test do
  gem 'capybara'
  gem "ffaker"
  gem 'rspec'
  gem 'machinist', "~>1.0.6"
  gem 'unicorn'
end
